export const recipes = [
    {
      name: "Spaghetti Carbonara",
      chef: "Chef Mario",
      totalRatings: 500,
      avgRating: 4.8,
      uploadedOn: "2024-01-15",
      mealType: "Dinner",
      dishType: "Pasta",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A classic Italian pasta dish with a creamy egg-based sauce and crispy pancetta.",
      imgUrl: "https://i.pinimg.com/564x/a9/0e/e4/a90ee4bca901e935a7a406a7d90ca6c2.jpg",
    },
    {
      name: "Grilled Salmon",
      chef: "Chef Julia",
      totalRatings: 350,
      avgRating: 4.6,
      uploadedOn: "2023-12-10",
      mealType: "Dinner",
      dishType: "Seafood",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Perfectly grilled salmon with a touch of lemon butter sauce and herbs.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJy7e7FNp7D3XHt8SSWKZyej_gLn9u60YFFQ&s",
    },
    {
      name: "Chocolate Lava Cake",
      chef: "Chef Pierre",
      totalRatings: 720,
      avgRating: 4.9,
      uploadedOn: "2024-02-20",
      mealType: "Dessert",
      dishType: "Cake",
      testKitchenApproved: true,
      contestWinner: true,
      featured: false,
      description: "A delicious molten chocolate lava cake that melts in your mouth.",
      imgUrl: "https://www.wearetateandlylesugars.com/wp-content/uploads/sites/2/2023/07/Chocolate-Lava-Cake-500-x-400_1.png",
    },
    {
      name: "Margherita Pizza",
      chef: "Chef Luigi",
      totalRatings: 610,
      avgRating: 4.7,
      uploadedOn: "2024-03-05",
      mealType: "Lunch",
      dishType: "Pizza",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A classic pizza topped with fresh mozzarella, basil, and tomatoes.",
      imgUrl: "https://safrescobaldistatic.blob.core.windows.net/media/2022/11/PIZZA-MARGHERITA.jpg",
    },
    {
      name: "Tandoori Chicken",
      chef: "Chef Ananya",
      totalRatings: 420,
      avgRating: 4.9,
      uploadedOn: "2024-03-10",
      mealType: "Dinner",
      dishType: "Grill",
      testKitchenApproved: false,
      contestWinner: true,
      featured: false,
      description: "Spicy grilled chicken marinated in yogurt and aromatic spices.",
      imgUrl: "https://www.cubesnjuliennes.com/wp-content/uploads/2022/12/Tandoori-Chicken-Recipe-500x375.jpg",
    },
    {
      name: "Caesar Salad",
      chef: "Chef Gordon",
      totalRatings: 280,
      avgRating: 4.5,
      uploadedOn: "2023-11-20",
      mealType: "Lunch",
      dishType: "Salad",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "Fresh romaine lettuce with parmesan, croutons, and Caesar dressing.",
      imgUrl: "https://www.grocery.coop/sites/default/files/NCG_Dennis_Becker_Classic_Caesar_Salad_715_x_477.jpg",
    },
    {
      name: "Sushi Platter",
      chef: "Chef Sato",
      totalRatings: 540,
      avgRating: 4.8,
      uploadedOn: "2024-02-05",
      mealType: "Dinner",
      dishType: "Sushi",
      testKitchenApproved: true,
      contestWinner: true,
      featured: false,
      description: "An assortment of fresh sushi rolls with soy sauce and wasabi.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqL7EP_U14Z7g1KaTiKcX_ROPAbSpQGI5-AQ&s",
    },
    {
      name: "Strawberry Cheesecake",
      chef: "Chef Emma",
      totalRatings: 480,
      avgRating: 4.9,
      uploadedOn: "2024-02-28",
      mealType: "Dessert",
      dishType: "Cake",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Creamy cheesecake with fresh strawberry topping.",
      imgUrl: "https://bakewithzoha.com/wp-content/uploads/2023/06/strawberry-cheesecake-featured.jpg",
    },
    {
      name: "Beef Tacos",
      chef: "Chef Ricardo",
      totalRatings: 390,
      avgRating: 4.7,
      uploadedOn: "2024-01-22",
      mealType: "Dinner",
      dishType: "Mexican",
      testKitchenApproved: false,
      contestWinner: false,
      featured: true,
      description: "Crispy beef tacos topped with salsa, cheese, and sour cream.",
      imgUrl: "https://www.onceuponachef.com/images/2023/08/Beef-Tacos.jpg",
    },
    {
      name: "Pancakes with Maple Syrup",
      chef: "Chef Olivia",
      totalRatings: 520,
      avgRating: 4.8,
      uploadedOn: "2024-03-01",
      mealType: "Breakfast",
      dishType: "Pancakes",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "Fluffy pancakes served with maple syrup and butter.",
      imgUrl: "https://cdn.tasteatlas.com/Images/Dishes/0b1a070027d1471196bbcdd8365df552.jpg",
    },
  ];
  